name: Terraform Apply

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Specify the path if .tf files are in a subdirectory

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
